version: "3"
services:
  metadata-db:
    image: postgres:10
    ports:
      - 5432:5432
    env_file:
      - pg.env

  airflow-init:
    build: .
    depends_on:
      - metadata-db
    command:
      - initdb
    env_file:
      - shared.env

  airflow-webserver:
    build: .
    restart: always
    command:
      - webserver
    env_file:
      - shared.env
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  airflow-scheduler:
    build: .
    restart: always
    command:
      - scheduler
    env_file:
      - shared.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/opt/airflow/docker.sock
